version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
  node-app:
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    build: 
      context: .
    command: npm start
    working_dir: /app
    environment:
      NODE_ENV: ${NODE_ENV}