const EMAIL_TEMPLATES = Object.freeze({
  WELCOME_EMAIL: 29108743,
  PHONE_NUMBER_RESET_OTP: 29108744,
  PHONE_NUMBER_RESET_SUCCESS: 29108507,
  PHONE_NUMBER_CHANGE_SUCCESS: 29108507,
  PASSWORD_CHANGE_SUCCESS: 29248096,
  PASSWORD_RESET_OTP: 29248123,
});
const PAGES = Object.freeze({
  HOME_PAGE: "Home Banner",
  LIVE_BANNER: "Live Event Banner",
  VIDEOS_BANNER: "Videos Banner",
  PRESS_BANNER: "News Banner",
  ADVERTISEMENT_BANNER: "Adverisement Banner",
  PARTNERSHIP_BANNER: "Partnership Banner",
  OFFERING_BANNER: "Offering Banner",
  CONTACT_BANNER: "Contact Banner",
  PROFILE_BANNER: "Profile Banner",
});
const USER_STATUS = Object.freeze({
  BLOCKED: "Blocked",
  ACTIVE: "Active",
  CONFIRMED: "Confirmed",
});
const SETTINGS_CATEGORIES = [
  PAGES.HOME_PAGE,
  PAGES.LIVE_BANNER,
  PAGES.VIDEOS_BANNER,
  PAGES.PRESS_BANNER,
  PAGES.ADVERTISEMENT_BANNER,
  PAGES.PARTNERSHIP_BANNER,
  PAGES.OFFERING_BANNER,
  PAGES.CONTACT_BANNER,
  PAGES.PROFILE_BANNER,
];
module.exports = { EMAIL_TEMPLATES, USER_STATUS, SETTINGS_CATEGORIES, PAGES };
